### ISSUE TITLE
[Typo] Typo found in `PMCaptha`

### ISSUE THREAD

**Issue by 01101sam** [TeamPGM/PagerMaid_Plugins_Pyro#121]
https://github.com/TeamPGM/PagerMaid_Plugins_Pyro/blob/055bc8dc74a1f6e5394ac0fab7f3bf83a1e5641d/pmcaptcha/main.py#L441

```diff
-<code>command</code<
+<code>command</code>
```

**Comment by omg-xtao** [comment]
fixed https://github.com/TeamPGM/PagerMaid_Plugins_Pyro/commit/2a1d9e33c11192740330f7622ab542c8353f4603
