### ISSUE TITLE
[Bug]: PMCaptcha会将Telegram系统消息视作用户发送的消息

### ISSUE THREAD

**Issue by pplulee** [TeamPGM/PagerMaid_Plugins_Pyro#167]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

v2.29

### 运行环境

Linux

### 运行架构

None

### 导致错误的插件是什么？

PMCaptcha

### 重现步骤

1. 用户A开启MathChallenge，并在Telegram-Setting-Privacy中启用Auto Delete Message，用户B尝试私聊用户A，会出现如下情况
![photo_2023-10-04_13-29-39](https://github.com/TeamPGM/PagerMaid_Plugins_Pyro/assets/46434255/61bf4c0d-8907-4493-bd42-b0712ba2dbc1)
---
2. 用户A开启MathChallenge，并在Telegram-Setting-Privacy中启用Auto Delete Message，用户B尝试私聊用户A，在得到验证问题后，修改Auto Delete的时间设置，再回复正确的答案，此时插件似乎无法正确识别用户的回复
![image_2023-10-04_13-54-26](https://github.com/TeamPGM/PagerMaid_Plugins_Pyro/assets/46434255/00bc7efd-855c-441d-9bdb-6a7719c12150)
![image_2023-10-04_13-54-31](https://github.com/TeamPGM/PagerMaid_Plugins_Pyro/assets/46434255/4dd7acf4-9a12-4b40-a212-827a960608cf)

### 期望的结果是什么？

插件在处理时跳过来自Telegram的消息

### 实际的结果是什么？

插件将来自Telegram消息视作用户消息

**Comment by omg-xtao** [comment]
cc @01101sam
