### ISSUE TITLE
[Bug]: ytdl插件因服务器IP疑似被YouTube标记而无法下载YouTube上的视频

### ISSUE THREAD

**Issue by BA7JCM** [TeamPGM/PagerMaid_Plugins_Pyro#186]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

93ab93a5ec29235172e497f84a6519f737807ccc

### 运行环境

Ubuntu

### 运行架构

AMD64

### 导致错误的插件是什么？

ytdl

### 重现步骤

正常安装并使用ytdl尝试下载任意YouTube上的视频，但由于问题因YouTube标记运行bot时所使用的服务器的IP导致，具体复现步骤因我无法确定怎样能稳定让YouTube标记特定IP而无法提供

### 期望的结果是什么？

正常下载到视频并通过telegram发送出来

### 实际的结果是什么？

```
下载/发送文件失败，发生错误：ERROR: [youtube] 视频id: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
```

### 补充说明（可选）

我猜可能要给插件加一个登录YouTube等平台的账号的入口，通过登录账号可能可以解决此问题？毕竟看报错里说的是“Sign in to confirm you’re not a bot”

**Comment by omg-xtao** [comment]
Your IP has been blocked by YouTube.
see https://github.com/yt-dlp/yt-dlp/issues/10128
