### ISSUE TITLE
[Feat]: pmcaptcha 自定义题目模板

### ISSUE THREAD

**Issue by sudoskys** [TeamPGM/PagerMaid_Plugins_Pyro#75]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 以及 [Pull Request](https://github.com/TeamPGM/PagerMaid-Pyro/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [x] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 这是一个什么样的功能？

在一些情况下，我需要确定私聊我的人在某个领域的水平，可以增加一个增强自定义性，自定义验证生成模板的特性吗？

[实现举例](https://github.com/TelechaBot/CaptchCore)

### 补充说明（可选）

貌似魔改 `MathChallenge(CaptchaChallenge)` 也可以实现

**Comment by 01101sam** [comment]
您好，`Captcha` 的初衷是为了让人类能够通过验证码而不是机器人通过
而您所提供的验证码范例不但能让机器人透过自动化程序强行通过，而且还会让一般人无法正常通过
对于此类验证码，大多数人都会避而远之，如果要使用这种验证码这边建议您直接开启 `disable_pm`

因此，您的请求已被驳回。

**Comment by zhxycn** [comment]
@01101sam
