### ISSUE TITLE
[Bug]: ip插件无法查询中文域名和ipv6

### ISSUE THREAD

**Issue by BLxcwg666** [TeamPGM/PagerMaid_Plugins_Pyro#90]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

2.0.51

### 运行环境

Linux

### 运行架构

x86

### 导致错误的插件是什么？

ip

### 重现步骤

,ip 油炸小陈.eu.org
没有找到要查询的 ip/域名 ...

,ip 240e:cf:8800:11:0:3e8:0:104
没有找到要查询的 ip/域名 ...

,ip [240e:cf:8800:11:0:3e8:0:104]
没有找到要查询的 ip/域名 ...

### 期望的结果是什么？

能用

### 实际的结果是什么？

不能用

**Comment by zhxycn** [comment]
请检查服务器是否能正常访问 ip-api.com

**Comment by zhxycn** [comment]
同时受上游api影响，仅支持ipv4查询
